### ISSUE TITLE
[Feature request] clangd integration

### ISSUE THREAD

**Issue by Pe13** [fridakitten/FridaCodeManager#10]
I know this is probably going to take a lot of time but I'd love if you could integrate clangd (at least on iPads that have more ram than iPhones), I don't think I need to explain how this could boost productivity.
(I'd like to contribute but I don't know Swift)

**Comment by Pe13** [comment]
If you would accept a c/cpp/obj-c contribution I'll take a look at how they interoperate, otherwise I had the plan to learn a little of swift and then learn during the process.

For your information clangd is a language server that is what gives you code completion, code navigation etc. etc. It is part of llvm and was built for iOS from procursus

**Comment by fridakitten** [comment]
Cool thing, but one quesion, do you want to make the code editor even slower than it is already? OwO

**Comment by Pe13** [comment]
Tbh I didn't noticed such a slowness (I never opened a big project, I don't have one)

**Comment by fridakitten** [comment]
The issue is also not that huge!

**Comment by fridakitten** [comment]
ClangD isisnt required anymore... view my latest tweet

**Comment by Pe13** [comment]
That seems great!!
What is that, sourcekit-lsp?
