### ISSUE TITLE
[Bug] Submit/Confirm buttons not showing on iPad

### ISSUE THREAD

**Issue by neht-net** [fridakitten/FridaCodeManager#12]
Version 1.6 doesn’t show submit/confirm buttons on iPad. 
![imageresizer_Oct252024194604_001](https://github.com/user-attachments/assets/7d7b54fc-30ee-4ba8-bc06-09dd7da81742)
![imageresizer_Oct252024194604_002](https://github.com/user-attachments/assets/4429cd84-5277-471c-8244-b4f486e404d8)
![imageresizer_Oct252024194604_003](https://github.com/user-attachments/assets/5aaf6ac2-7fb0-4b48-b226-cd03ca7919bb)

**Comment by fridakitten** [comment]
Ouff, will be hard to fix. FCM doesn’t support iPad yet. iPad is totally different!

**Comment by fridakitten** [comment]
Its expecting fulls creek to be used for that popup. The iPad doesn’t do that tho. I have no iPad for debugging :c

**Comment by neht-net** [comment]
These popups were working well in previous versions though. I’ll give feedback on iPad compatibility as soon as new version is released. 
Thanks!

**Comment by fridakitten** [comment]
these popups were extremely broken for all devices in previous versions

**Comment by fridakitten** [comment]
is fixed in FCM v1.7
