### ISSUE TITLE
Suggestion: Maybe use Runestone to save dev time with code editor

### ISSUE THREAD

**Issue by jawshoeadan** [fridakitten/FridaCodeManager#13]
https://github.com/simonbs/Runestone

Obviously up to you but it seems like this library has a lot of the functionality you're looking for

**Comment by fridakitten** [comment]
I decline this offer as Rhinestone has not the functionalities I need for FCM. it must be fully compatible with FCM. errorcache linkage, etc. I try to give you guys the best experience possible while also learn how to do it my self. but I appreciate that you told me about runestone. I think runestone is a bit bloated tbh. unnecessary things are in it. FCM uses NSRegex patterns and runestone uses treesetter.... tree setter isint this great,
