### ISSUE TITLE
Can't build on roothide

### ISSUE THREAD

**Issue by Pe13** [fridakitten/FridaCodeManager#18]
Since at the moment roothide provides llvm-14 instead of llvm-16, hard coded values like [this](https://github.com/fridakitten/FridaCodeManager/blob/071635dc56412b97939d3e5fa0da79fe3247b2f5/Makefile#L18) (this is not the only one) block the build on roothide.

**Comment by fridakitten** [comment]
tell root hide to update to llvm 16 as that's the new standard

**Comment by fridakitten** [comment]
when I use -lclang then it will link against a unsigned wrapper of libclang that makes a process that depends on it crash
