### ISSUE TITLE
iPad 7th gen 17.5.1 [can’t create project]

### ISSUE THREAD

**Issue by igamegod** [fridakitten/FridaCodeManager#22]
When I try creating the project the ui seems to not show the rest of it.

Landscape - 
![IMG_0004](https://github.com/user-attachments/assets/4c24acbc-36d9-4b00-992e-767bbf2d80b0)

Portrait - 
![IMG_0005](https://github.com/user-attachments/assets/0557acd7-cf25-46c5-ae0d-907f670498d3)

**Comment by fridakitten** [comment]
already fixed in v1.7
