### ISSUE TITLE
Swift Package Manager Integration: Add Multiple Packages

### ISSUE THREAD

**Issue by Youngolo** [fridakitten/FridaCodeManager#23]
Hello, thank you for your wonderful project!

I am currently using `FridaCodeManager` to learn app development, and I need to integrate several Swift packages, such as the `PythonKit` library to execute Python scripts within my SwiftUI application. However, I am encountering difficulties figuring out how to add these packages using Swift Package Manager within `FridaCodeManager`.

**Steps to reproduce the issue**:
1. Open the project using `FridaCodeManager`.
2. Attempt to add multiple Swift packages, such as `PythonKit`, using their respective URLs via Swift Package Manager.
3. Encounter build errors with messages like `no such module 'PythonKit'`.

**Expected behavior**:
I would like to know the correct steps or methods to successfully integrate multiple Swift packages using Swift Package Manager within `FridaCodeManager`, similar to the process in Xcode.

**Environment**:
- `FridaCodeManager` version: 1.6
- iOS version: 16.3

**Additional context**:
Any guidance or documentation on this would be greatly appreciated. Here are the URLs of the packages I need to integrate:
- `PythonKit`: `https://github.com/pvieito/PythonKit.git`
- [Add other package URLs here]

Thank you for your support!

---

Thank you in advance for your assistance!

**Comment by fridakitten** [comment]
That's not a bug
