### ISSUE TITLE
i am not able to installa the deb file

### ISSUE THREAD

**Issue by codecpacka** [fridakitten/FridaCodeManager#4]
hello developers,
i am not able to install the deb file on my jailbroken iphone 6s+ ios**(15.8.0)** ,kindly provide me with a solution ,below i am attaching a screenshot of the error i am facing
![frida](https://github.com/fridakitten/FridaCodeManager/assets/32800467/9bc53b13-783f-44e8-95b7-9b8919eea351)

**Comment by fridakitten** [comment]
What jailbreak are you using. If roothide you should make sure to install the roothide package and if it is rootless ensure you have added procursus repo!

**Comment by codecpacka** [comment]
i am using  paler1n jailbreak( rootfull)

**Comment by fridakitten** [comment]
Yeah, rootful is not supported and will never be, rootful is too old, please upgrade to rootless.

**Comment by ghh-jb** [comment]
Fuck you. Rootful is not dead.

**Comment by ghh-jb** [comment]
I will try to make it rootful

**Comment by codecpacka** [comment]
thanks but now i switched to rootless still u can make a rootful version
for future use
