### ISSUE TITLE
Line numbers?

### ISSUE THREAD

**Issue by ghh-jb** [fridakitten/FridaCodeManager#6]
I need line numeration to navigate in code. It is not really comfortable to read plain text even with highlighting. Please add:)

**Comment by fridakitten** [comment]
Line numeration is at the ToolBar of the Keyboard. Its on purpose at this specific spot as iPhone screens width is not that huge and especially if a dev has 1000 lines of code the bar can get really thick. move the cursor :3

**Comment by ghh-jb** [comment]
OMG. Loke if you have > 1000 lines of code you can make them
1k
2k
10k
Etc. 

I dont think that devs write more than 10^6 lines of code:)

**Comment by ghh-jb** [comment]
Pity. Very pity.

**Comment by ghh-jb** [comment]
Maybe option to enable/disable line numeration?

**Comment by fridakitten** [comment]
Do you want to loose 20 FPS more?

**Comment by ghh-jb** [comment]
I dont care:)))
Jetsam will make it better any if you need 60 FPS stable you will be able to disable numeration.:)

**Comment by ghh-jb** [comment]
> Do you want to loose 20 FPS more?

Just make settings page for it and some maybe other settings.

**Comment by fridakitten** [comment]
Jetsam?? On a already native process?? This makes no sense

**Comment by ghh-jb** [comment]
> Jetsam?? On a already native process?? This makes no sense

Yep. That was stup1d. My fault:) Heh. Like if you dont want to add numeration for like any reason ill close an issue.
