### ISSUE TITLE
Issue with SDK download in FridaCodeManager

### ISSUE THREAD

**Issue by Youngolo** [fridakitten/FridaCodeManager#7]
Hi,
I recently installed FridaCodeManager and attempted to build an app. However, I encountered a problem in the SDK Hub where I need to download the SDK.    When I click on the download button, nothing happens.    There is no progress or error message displayed.
Here are the details of the issue:
- FridaCodeManager version: 1.5.2
- iOS version: ios16.3
- Device model: iphone12
- Steps to reproduce:
1.    Open FridaCodeManager.
2.    Navigate to the SDK Hub.
3.    Select the required SDK.
4.    Click on the download button.
- Expected result: The SDK should start downloading.
- Actual result: Nothing happens after clicking the download button.
Could you please assist me with this issue?    Is there a workaround or additional steps I should take to download the SDK successfully?

**Comment by Pe13** [comment]
Personally I discovered FCM today and I built the latest version of the repo (nothing about sdk download changed).
I was trying to build the template OBJ-C app so I downloaded the 16.5 sdk and the download was fine.
Iirc there was no progress bar but from Helium bar I could see that it was downloading something and in less than a minute I got my sdk.

I'm on an iPad Air 5th gen iOS 16.6 roothide

**Comment by fridakitten** [comment]
I could be your internet speed, if your internet is too slow it will timeout for performance purposes

**Comment by Youngolo** [comment]
After clicking to download the SDK, Helium did not detect any network fluctuations. Through packet capturing, it was found that after clicking to download the SDK, there was only a request to https://polcom.de.

**Comment by fridakitten** [comment]
libfload should fix this
