### ISSUE TITLE
Lacking a Mac computer, I am confined to using a Windows machine.  I’m in search of solutions to edit and debug iOS apps on Windows using vscode-server, while encountering permission issues.

### ISSUE THREAD

**Issue by Youngolo** [fridakitten/FridaCodeManager#8]
I don’t have a Mac computer;  I only have Windows.  Is it possible to edit and debug using vscode-server?  For example, this package: code-server - sileo://package/alias20. code-server - from https://alias20.gitlab.io/apt/ It can start a vscode-server service, allowing for the editing of various files in the browser and debugging using the terminal.

My current plan is to apply the vscode-server service to the application directory, but I’m unsure why I don’t have the necessary permissions:

Young:/var/mobile/Containers/Data/Application mobile% ls
ls: cannot open directory '. ': Operation not permitted
Young:/var/mobile/Containers/Data/Application mobile% cd ../
Young:/var/mobile/Containers/Data mobile% ls
ls: cannot open directory '. ': Operation not permitted
Young:/var/mobile/Containers/Data mobile% cd ../
Young:/var/mobile/Containers mobile% ls
Data/  Shared/  Staging/  Temp/
Young:/var/mobile/Containers mobile%
Even switching to the root user does not grant permissions:

Young:/var/mobile/Containers/Data/Application root# ls
ls: cannot open directory '. ': Operation not permitted
Young:/var/mobile/Containers/Data/Application root# pwd
/var/mobile/Containers/Data/Application
Young:/var/mobile/Containers/Data/Application root# id
uid=0(root) gid=0(wheel) groups=0(wheel)
Young:/var/mobile/Containers/Data/Application root# whoami
root
Young:/var/mobile/Containers/Data/Application root#
Can you solve this issue or suggest a better method?

**Comment by fridakitten** [comment]
This cannot be a FridaCodeManager issue, this is mostlikely a skill issue.
